---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: prometheus-custom-exporter
  static_configs:
  - targets: ["prometheus-custom-exporter:9150"]